package com.example.demo.bo;

import java.util.Date;

public class CCons {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CONS_ID
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String consId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CUST_ID
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CONS_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String consNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CONS_NAME
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String consName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CUST_QUERY_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String custQueryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.TMP_PAY_RELA_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String tmpPayRelaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.ORGN_CONS_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String orgnConsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CONS_SORT_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String consSortCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.ELEC_ADDR
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String elecAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.TRADE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String tradeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.ELEC_TYPE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String elecTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CONTRACT_CAP
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private Double contractCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.RUN_CAP
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private Double runCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.SHIFT_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String shiftNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.LODE_ATTR_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String lodeAttrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.VOLT_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String voltCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.HEC_INDUSTRY_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String hecIndustryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.HOLIDAY
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String holiday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.BUILD_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private Date buildDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.PS_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private Date psDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.DUE_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private Date dueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.NOTIFY_MODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String notifyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.SETTLE_MODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String settleMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.STATUS_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.ORG_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String orgNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.RRIO_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String rrioCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CHK_CYCLE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String chkCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.LAST_CHK_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private Date lastChkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.CHECER_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String checerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.POWEROFF_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String poweroffCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.TRANSFER_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String transferCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.MR_SECT_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String mrSectNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.NOTE_TYPE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String noteTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.TMP_FLAG
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private String tmpFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cons.TMP_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    private Date tmpDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CONS_ID
     *
     * @return the value of c_cons.CONS_ID
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getConsId() {
        return consId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CONS_ID
     *
     * @param consId the value for c_cons.CONS_ID
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setConsId(String consId) {
        this.consId = consId == null ? null : consId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CUST_ID
     *
     * @return the value of c_cons.CUST_ID
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CUST_ID
     *
     * @param custId the value for c_cons.CUST_ID
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CONS_NO
     *
     * @return the value of c_cons.CONS_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getConsNo() {
        return consNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CONS_NO
     *
     * @param consNo the value for c_cons.CONS_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setConsNo(String consNo) {
        this.consNo = consNo == null ? null : consNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CONS_NAME
     *
     * @return the value of c_cons.CONS_NAME
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getConsName() {
        return consName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CONS_NAME
     *
     * @param consName the value for c_cons.CONS_NAME
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setConsName(String consName) {
        this.consName = consName == null ? null : consName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CUST_QUERY_NO
     *
     * @return the value of c_cons.CUST_QUERY_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getCustQueryNo() {
        return custQueryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CUST_QUERY_NO
     *
     * @param custQueryNo the value for c_cons.CUST_QUERY_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setCustQueryNo(String custQueryNo) {
        this.custQueryNo = custQueryNo == null ? null : custQueryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.TMP_PAY_RELA_NO
     *
     * @return the value of c_cons.TMP_PAY_RELA_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getTmpPayRelaNo() {
        return tmpPayRelaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.TMP_PAY_RELA_NO
     *
     * @param tmpPayRelaNo the value for c_cons.TMP_PAY_RELA_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setTmpPayRelaNo(String tmpPayRelaNo) {
        this.tmpPayRelaNo = tmpPayRelaNo == null ? null : tmpPayRelaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.ORGN_CONS_NO
     *
     * @return the value of c_cons.ORGN_CONS_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getOrgnConsNo() {
        return orgnConsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.ORGN_CONS_NO
     *
     * @param orgnConsNo the value for c_cons.ORGN_CONS_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setOrgnConsNo(String orgnConsNo) {
        this.orgnConsNo = orgnConsNo == null ? null : orgnConsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CONS_SORT_CODE
     *
     * @return the value of c_cons.CONS_SORT_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getConsSortCode() {
        return consSortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CONS_SORT_CODE
     *
     * @param consSortCode the value for c_cons.CONS_SORT_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setConsSortCode(String consSortCode) {
        this.consSortCode = consSortCode == null ? null : consSortCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.ELEC_ADDR
     *
     * @return the value of c_cons.ELEC_ADDR
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getElecAddr() {
        return elecAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.ELEC_ADDR
     *
     * @param elecAddr the value for c_cons.ELEC_ADDR
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setElecAddr(String elecAddr) {
        this.elecAddr = elecAddr == null ? null : elecAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.TRADE_CODE
     *
     * @return the value of c_cons.TRADE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getTradeCode() {
        return tradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.TRADE_CODE
     *
     * @param tradeCode the value for c_cons.TRADE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setTradeCode(String tradeCode) {
        this.tradeCode = tradeCode == null ? null : tradeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.ELEC_TYPE_CODE
     *
     * @return the value of c_cons.ELEC_TYPE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getElecTypeCode() {
        return elecTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.ELEC_TYPE_CODE
     *
     * @param elecTypeCode the value for c_cons.ELEC_TYPE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setElecTypeCode(String elecTypeCode) {
        this.elecTypeCode = elecTypeCode == null ? null : elecTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CONTRACT_CAP
     *
     * @return the value of c_cons.CONTRACT_CAP
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Double getContractCap() {
        return contractCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CONTRACT_CAP
     *
     * @param contractCap the value for c_cons.CONTRACT_CAP
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setContractCap(Double contractCap) {
        this.contractCap = contractCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.RUN_CAP
     *
     * @return the value of c_cons.RUN_CAP
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Double getRunCap() {
        return runCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.RUN_CAP
     *
     * @param runCap the value for c_cons.RUN_CAP
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setRunCap(Double runCap) {
        this.runCap = runCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.SHIFT_NO
     *
     * @return the value of c_cons.SHIFT_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getShiftNo() {
        return shiftNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.SHIFT_NO
     *
     * @param shiftNo the value for c_cons.SHIFT_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setShiftNo(String shiftNo) {
        this.shiftNo = shiftNo == null ? null : shiftNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.LODE_ATTR_CODE
     *
     * @return the value of c_cons.LODE_ATTR_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getLodeAttrCode() {
        return lodeAttrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.LODE_ATTR_CODE
     *
     * @param lodeAttrCode the value for c_cons.LODE_ATTR_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setLodeAttrCode(String lodeAttrCode) {
        this.lodeAttrCode = lodeAttrCode == null ? null : lodeAttrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.VOLT_CODE
     *
     * @return the value of c_cons.VOLT_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getVoltCode() {
        return voltCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.VOLT_CODE
     *
     * @param voltCode the value for c_cons.VOLT_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setVoltCode(String voltCode) {
        this.voltCode = voltCode == null ? null : voltCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.HEC_INDUSTRY_CODE
     *
     * @return the value of c_cons.HEC_INDUSTRY_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getHecIndustryCode() {
        return hecIndustryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.HEC_INDUSTRY_CODE
     *
     * @param hecIndustryCode the value for c_cons.HEC_INDUSTRY_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setHecIndustryCode(String hecIndustryCode) {
        this.hecIndustryCode = hecIndustryCode == null ? null : hecIndustryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.HOLIDAY
     *
     * @return the value of c_cons.HOLIDAY
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getHoliday() {
        return holiday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.HOLIDAY
     *
     * @param holiday the value for c_cons.HOLIDAY
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setHoliday(String holiday) {
        this.holiday = holiday == null ? null : holiday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.BUILD_DATE
     *
     * @return the value of c_cons.BUILD_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Date getBuildDate() {
        return buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.BUILD_DATE
     *
     * @param buildDate the value for c_cons.BUILD_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setBuildDate(Date buildDate) {
        this.buildDate = buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.PS_DATE
     *
     * @return the value of c_cons.PS_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Date getPsDate() {
        return psDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.PS_DATE
     *
     * @param psDate the value for c_cons.PS_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setPsDate(Date psDate) {
        this.psDate = psDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.DUE_DATE
     *
     * @return the value of c_cons.DUE_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.DUE_DATE
     *
     * @param dueDate the value for c_cons.DUE_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.NOTIFY_MODE
     *
     * @return the value of c_cons.NOTIFY_MODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getNotifyMode() {
        return notifyMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.NOTIFY_MODE
     *
     * @param notifyMode the value for c_cons.NOTIFY_MODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setNotifyMode(String notifyMode) {
        this.notifyMode = notifyMode == null ? null : notifyMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.SETTLE_MODE
     *
     * @return the value of c_cons.SETTLE_MODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getSettleMode() {
        return settleMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.SETTLE_MODE
     *
     * @param settleMode the value for c_cons.SETTLE_MODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setSettleMode(String settleMode) {
        this.settleMode = settleMode == null ? null : settleMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.STATUS_CODE
     *
     * @return the value of c_cons.STATUS_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.STATUS_CODE
     *
     * @param statusCode the value for c_cons.STATUS_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.ORG_NO
     *
     * @return the value of c_cons.ORG_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.ORG_NO
     *
     * @param orgNo the value for c_cons.ORG_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo == null ? null : orgNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.RRIO_CODE
     *
     * @return the value of c_cons.RRIO_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getRrioCode() {
        return rrioCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.RRIO_CODE
     *
     * @param rrioCode the value for c_cons.RRIO_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setRrioCode(String rrioCode) {
        this.rrioCode = rrioCode == null ? null : rrioCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CHK_CYCLE
     *
     * @return the value of c_cons.CHK_CYCLE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getChkCycle() {
        return chkCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CHK_CYCLE
     *
     * @param chkCycle the value for c_cons.CHK_CYCLE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setChkCycle(String chkCycle) {
        this.chkCycle = chkCycle == null ? null : chkCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.LAST_CHK_DATE
     *
     * @return the value of c_cons.LAST_CHK_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Date getLastChkDate() {
        return lastChkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.LAST_CHK_DATE
     *
     * @param lastChkDate the value for c_cons.LAST_CHK_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setLastChkDate(Date lastChkDate) {
        this.lastChkDate = lastChkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.CHECER_NO
     *
     * @return the value of c_cons.CHECER_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getChecerNo() {
        return checerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.CHECER_NO
     *
     * @param checerNo the value for c_cons.CHECER_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setChecerNo(String checerNo) {
        this.checerNo = checerNo == null ? null : checerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.POWEROFF_CODE
     *
     * @return the value of c_cons.POWEROFF_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getPoweroffCode() {
        return poweroffCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.POWEROFF_CODE
     *
     * @param poweroffCode the value for c_cons.POWEROFF_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setPoweroffCode(String poweroffCode) {
        this.poweroffCode = poweroffCode == null ? null : poweroffCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.TRANSFER_CODE
     *
     * @return the value of c_cons.TRANSFER_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getTransferCode() {
        return transferCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.TRANSFER_CODE
     *
     * @param transferCode the value for c_cons.TRANSFER_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setTransferCode(String transferCode) {
        this.transferCode = transferCode == null ? null : transferCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.MR_SECT_NO
     *
     * @return the value of c_cons.MR_SECT_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getMrSectNo() {
        return mrSectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.MR_SECT_NO
     *
     * @param mrSectNo the value for c_cons.MR_SECT_NO
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setMrSectNo(String mrSectNo) {
        this.mrSectNo = mrSectNo == null ? null : mrSectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.NOTE_TYPE_CODE
     *
     * @return the value of c_cons.NOTE_TYPE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getNoteTypeCode() {
        return noteTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.NOTE_TYPE_CODE
     *
     * @param noteTypeCode the value for c_cons.NOTE_TYPE_CODE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setNoteTypeCode(String noteTypeCode) {
        this.noteTypeCode = noteTypeCode == null ? null : noteTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.TMP_FLAG
     *
     * @return the value of c_cons.TMP_FLAG
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getTmpFlag() {
        return tmpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.TMP_FLAG
     *
     * @param tmpFlag the value for c_cons.TMP_FLAG
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setTmpFlag(String tmpFlag) {
        this.tmpFlag = tmpFlag == null ? null : tmpFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cons.TMP_DATE
     *
     * @return the value of c_cons.TMP_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Date getTmpDate() {
        return tmpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cons.TMP_DATE
     *
     * @param tmpDate the value for c_cons.TMP_DATE
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setTmpDate(Date tmpDate) {
        this.tmpDate = tmpDate;
    }

    @Override
    public String toString() {
        return "CCons{" +
                "consId='" + consId + '\'' +
                ", custId='" + custId + '\'' +
                ", consNo='" + consNo + '\'' +
                ", consName='" + consName + '\'' +
                ", custQueryNo='" + custQueryNo + '\'' +
                ", tmpPayRelaNo='" + tmpPayRelaNo + '\'' +
                ", orgnConsNo='" + orgnConsNo + '\'' +
                ", consSortCode='" + consSortCode + '\'' +
                ", elecAddr='" + elecAddr + '\'' +
                ", tradeCode='" + tradeCode + '\'' +
                ", elecTypeCode='" + elecTypeCode + '\'' +
                ", contractCap=" + contractCap +
                ", runCap=" + runCap +
                ", shiftNo='" + shiftNo + '\'' +
                ", lodeAttrCode='" + lodeAttrCode + '\'' +
                ", voltCode='" + voltCode + '\'' +
                ", hecIndustryCode='" + hecIndustryCode + '\'' +
                ", holiday='" + holiday + '\'' +
                ", buildDate=" + buildDate +
                ", psDate=" + psDate +
                ", dueDate=" + dueDate +
                ", notifyMode='" + notifyMode + '\'' +
                ", settleMode='" + settleMode + '\'' +
                ", statusCode='" + statusCode + '\'' +
                ", orgNo='" + orgNo + '\'' +
                ", rrioCode='" + rrioCode + '\'' +
                ", chkCycle='" + chkCycle + '\'' +
                ", lastChkDate=" + lastChkDate +
                ", checerNo='" + checerNo + '\'' +
                ", poweroffCode='" + poweroffCode + '\'' +
                ", transferCode='" + transferCode + '\'' +
                ", mrSectNo='" + mrSectNo + '\'' +
                ", noteTypeCode='" + noteTypeCode + '\'' +
                ", tmpFlag='" + tmpFlag + '\'' +
                ", tmpDate=" + tmpDate +
                '}';
    }
}