package com.example.demo.bo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CConsExtExample {
    private  String startRow;

    private  String pageSize;

    public String getStartRow() {
        return startRow;
    }

    public void setStartRow(String startRow) {
        this.startRow = startRow;
    }

    public String getPageSize() {
        return pageSize;
    }

    public void setPageSize(String pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public CConsExtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andConsIdIsNull() {
            addCriterion("CONS_ID is null");
            return (Criteria) this;
        }

        public Criteria andConsIdIsNotNull() {
            addCriterion("CONS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andConsIdEqualTo(String value) {
            addCriterion("CONS_ID =", value, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdNotEqualTo(String value) {
            addCriterion("CONS_ID <>", value, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdGreaterThan(String value) {
            addCriterion("CONS_ID >", value, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdGreaterThanOrEqualTo(String value) {
            addCriterion("CONS_ID >=", value, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdLessThan(String value) {
            addCriterion("CONS_ID <", value, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdLessThanOrEqualTo(String value) {
            addCriterion("CONS_ID <=", value, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdLike(String value) {
            addCriterion("CONS_ID like", value, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdNotLike(String value) {
            addCriterion("CONS_ID not like", value, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdIn(List<String> values) {
            addCriterion("CONS_ID in", values, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdNotIn(List<String> values) {
            addCriterion("CONS_ID not in", values, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdBetween(String value1, String value2) {
            addCriterion("CONS_ID between", value1, value2, "consId");
            return (Criteria) this;
        }

        public Criteria andConsIdNotBetween(String value1, String value2) {
            addCriterion("CONS_ID not between", value1, value2, "consId");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("CUST_ID is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("CUST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(String value) {
            addCriterion("CUST_ID =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(String value) {
            addCriterion("CUST_ID <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(String value) {
            addCriterion("CUST_ID >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_ID >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(String value) {
            addCriterion("CUST_ID <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(String value) {
            addCriterion("CUST_ID <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLike(String value) {
            addCriterion("CUST_ID like", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotLike(String value) {
            addCriterion("CUST_ID not like", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<String> values) {
            addCriterion("CUST_ID in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<String> values) {
            addCriterion("CUST_ID not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(String value1, String value2) {
            addCriterion("CUST_ID between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(String value1, String value2) {
            addCriterion("CUST_ID not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andConsNoIsNull() {
            addCriterion("CONS_NO is null");
            return (Criteria) this;
        }

        public Criteria andConsNoIsNotNull() {
            addCriterion("CONS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andConsNoEqualTo(String value) {
            addCriterion("CONS_NO =", value, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoNotEqualTo(String value) {
            addCriterion("CONS_NO <>", value, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoGreaterThan(String value) {
            addCriterion("CONS_NO >", value, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoGreaterThanOrEqualTo(String value) {
            addCriterion("CONS_NO >=", value, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoLessThan(String value) {
            addCriterion("CONS_NO <", value, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoLessThanOrEqualTo(String value) {
            addCriterion("CONS_NO <=", value, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoLike(String value) {
            addCriterion("CONS_NO like", value, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoNotLike(String value) {
            addCriterion("CONS_NO not like", value, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoIn(List<String> values) {
            addCriterion("CONS_NO in", values, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoNotIn(List<String> values) {
            addCriterion("CONS_NO not in", values, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoBetween(String value1, String value2) {
            addCriterion("CONS_NO between", value1, value2, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNoNotBetween(String value1, String value2) {
            addCriterion("CONS_NO not between", value1, value2, "consNo");
            return (Criteria) this;
        }

        public Criteria andConsNameIsNull() {
            addCriterion("CONS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andConsNameIsNotNull() {
            addCriterion("CONS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andConsNameEqualTo(String value) {
            addCriterion("CONS_NAME =", value, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameNotEqualTo(String value) {
            addCriterion("CONS_NAME <>", value, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameGreaterThan(String value) {
            addCriterion("CONS_NAME >", value, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameGreaterThanOrEqualTo(String value) {
            addCriterion("CONS_NAME >=", value, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameLessThan(String value) {
            addCriterion("CONS_NAME <", value, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameLessThanOrEqualTo(String value) {
            addCriterion("CONS_NAME <=", value, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameLike(String value) {
            addCriterion("CONS_NAME like", value, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameNotLike(String value) {
            addCriterion("CONS_NAME not like", value, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameIn(List<String> values) {
            addCriterion("CONS_NAME in", values, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameNotIn(List<String> values) {
            addCriterion("CONS_NAME not in", values, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameBetween(String value1, String value2) {
            addCriterion("CONS_NAME between", value1, value2, "consName");
            return (Criteria) this;
        }

        public Criteria andConsNameNotBetween(String value1, String value2) {
            addCriterion("CONS_NAME not between", value1, value2, "consName");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoIsNull() {
            addCriterion("CUST_QUERY_NO is null");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoIsNotNull() {
            addCriterion("CUST_QUERY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoEqualTo(String value) {
            addCriterion("CUST_QUERY_NO =", value, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoNotEqualTo(String value) {
            addCriterion("CUST_QUERY_NO <>", value, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoGreaterThan(String value) {
            addCriterion("CUST_QUERY_NO >", value, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_QUERY_NO >=", value, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoLessThan(String value) {
            addCriterion("CUST_QUERY_NO <", value, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoLessThanOrEqualTo(String value) {
            addCriterion("CUST_QUERY_NO <=", value, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoLike(String value) {
            addCriterion("CUST_QUERY_NO like", value, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoNotLike(String value) {
            addCriterion("CUST_QUERY_NO not like", value, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoIn(List<String> values) {
            addCriterion("CUST_QUERY_NO in", values, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoNotIn(List<String> values) {
            addCriterion("CUST_QUERY_NO not in", values, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoBetween(String value1, String value2) {
            addCriterion("CUST_QUERY_NO between", value1, value2, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andCustQueryNoNotBetween(String value1, String value2) {
            addCriterion("CUST_QUERY_NO not between", value1, value2, "custQueryNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoIsNull() {
            addCriterion("TMP_PAY_RELA_NO is null");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoIsNotNull() {
            addCriterion("TMP_PAY_RELA_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoEqualTo(String value) {
            addCriterion("TMP_PAY_RELA_NO =", value, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoNotEqualTo(String value) {
            addCriterion("TMP_PAY_RELA_NO <>", value, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoGreaterThan(String value) {
            addCriterion("TMP_PAY_RELA_NO >", value, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoGreaterThanOrEqualTo(String value) {
            addCriterion("TMP_PAY_RELA_NO >=", value, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoLessThan(String value) {
            addCriterion("TMP_PAY_RELA_NO <", value, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoLessThanOrEqualTo(String value) {
            addCriterion("TMP_PAY_RELA_NO <=", value, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoLike(String value) {
            addCriterion("TMP_PAY_RELA_NO like", value, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoNotLike(String value) {
            addCriterion("TMP_PAY_RELA_NO not like", value, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoIn(List<String> values) {
            addCriterion("TMP_PAY_RELA_NO in", values, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoNotIn(List<String> values) {
            addCriterion("TMP_PAY_RELA_NO not in", values, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoBetween(String value1, String value2) {
            addCriterion("TMP_PAY_RELA_NO between", value1, value2, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andTmpPayRelaNoNotBetween(String value1, String value2) {
            addCriterion("TMP_PAY_RELA_NO not between", value1, value2, "tmpPayRelaNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoIsNull() {
            addCriterion("ORGN_CONS_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoIsNotNull() {
            addCriterion("ORGN_CONS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoEqualTo(String value) {
            addCriterion("ORGN_CONS_NO =", value, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoNotEqualTo(String value) {
            addCriterion("ORGN_CONS_NO <>", value, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoGreaterThan(String value) {
            addCriterion("ORGN_CONS_NO >", value, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORGN_CONS_NO >=", value, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoLessThan(String value) {
            addCriterion("ORGN_CONS_NO <", value, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoLessThanOrEqualTo(String value) {
            addCriterion("ORGN_CONS_NO <=", value, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoLike(String value) {
            addCriterion("ORGN_CONS_NO like", value, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoNotLike(String value) {
            addCriterion("ORGN_CONS_NO not like", value, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoIn(List<String> values) {
            addCriterion("ORGN_CONS_NO in", values, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoNotIn(List<String> values) {
            addCriterion("ORGN_CONS_NO not in", values, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoBetween(String value1, String value2) {
            addCriterion("ORGN_CONS_NO between", value1, value2, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andOrgnConsNoNotBetween(String value1, String value2) {
            addCriterion("ORGN_CONS_NO not between", value1, value2, "orgnConsNo");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeIsNull() {
            addCriterion("CONS_SORT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeIsNotNull() {
            addCriterion("CONS_SORT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeEqualTo(String value) {
            addCriterion("CONS_SORT_CODE =", value, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeNotEqualTo(String value) {
            addCriterion("CONS_SORT_CODE <>", value, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeGreaterThan(String value) {
            addCriterion("CONS_SORT_CODE >", value, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CONS_SORT_CODE >=", value, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeLessThan(String value) {
            addCriterion("CONS_SORT_CODE <", value, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeLessThanOrEqualTo(String value) {
            addCriterion("CONS_SORT_CODE <=", value, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeLike(String value) {
            addCriterion("CONS_SORT_CODE like", value, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeNotLike(String value) {
            addCriterion("CONS_SORT_CODE not like", value, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeIn(List<String> values) {
            addCriterion("CONS_SORT_CODE in", values, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeNotIn(List<String> values) {
            addCriterion("CONS_SORT_CODE not in", values, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeBetween(String value1, String value2) {
            addCriterion("CONS_SORT_CODE between", value1, value2, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andConsSortCodeNotBetween(String value1, String value2) {
            addCriterion("CONS_SORT_CODE not between", value1, value2, "consSortCode");
            return (Criteria) this;
        }

        public Criteria andElecAddrIsNull() {
            addCriterion("ELEC_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andElecAddrIsNotNull() {
            addCriterion("ELEC_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andElecAddrEqualTo(String value) {
            addCriterion("ELEC_ADDR =", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotEqualTo(String value) {
            addCriterion("ELEC_ADDR <>", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrGreaterThan(String value) {
            addCriterion("ELEC_ADDR >", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ELEC_ADDR >=", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLessThan(String value) {
            addCriterion("ELEC_ADDR <", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLessThanOrEqualTo(String value) {
            addCriterion("ELEC_ADDR <=", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLike(String value) {
            addCriterion("ELEC_ADDR like", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotLike(String value) {
            addCriterion("ELEC_ADDR not like", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrIn(List<String> values) {
            addCriterion("ELEC_ADDR in", values, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotIn(List<String> values) {
            addCriterion("ELEC_ADDR not in", values, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrBetween(String value1, String value2) {
            addCriterion("ELEC_ADDR between", value1, value2, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotBetween(String value1, String value2) {
            addCriterion("ELEC_ADDR not between", value1, value2, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andTradeCodeIsNull() {
            addCriterion("TRADE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTradeCodeIsNotNull() {
            addCriterion("TRADE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeCodeEqualTo(String value) {
            addCriterion("TRADE_CODE =", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeNotEqualTo(String value) {
            addCriterion("TRADE_CODE <>", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeGreaterThan(String value) {
            addCriterion("TRADE_CODE >", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_CODE >=", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeLessThan(String value) {
            addCriterion("TRADE_CODE <", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_CODE <=", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeLike(String value) {
            addCriterion("TRADE_CODE like", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeNotLike(String value) {
            addCriterion("TRADE_CODE not like", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeIn(List<String> values) {
            addCriterion("TRADE_CODE in", values, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeNotIn(List<String> values) {
            addCriterion("TRADE_CODE not in", values, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeBetween(String value1, String value2) {
            addCriterion("TRADE_CODE between", value1, value2, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeNotBetween(String value1, String value2) {
            addCriterion("TRADE_CODE not between", value1, value2, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeIsNull() {
            addCriterion("ELEC_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeIsNotNull() {
            addCriterion("ELEC_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeEqualTo(String value) {
            addCriterion("ELEC_TYPE_CODE =", value, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeNotEqualTo(String value) {
            addCriterion("ELEC_TYPE_CODE <>", value, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeGreaterThan(String value) {
            addCriterion("ELEC_TYPE_CODE >", value, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ELEC_TYPE_CODE >=", value, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeLessThan(String value) {
            addCriterion("ELEC_TYPE_CODE <", value, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("ELEC_TYPE_CODE <=", value, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeLike(String value) {
            addCriterion("ELEC_TYPE_CODE like", value, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeNotLike(String value) {
            addCriterion("ELEC_TYPE_CODE not like", value, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeIn(List<String> values) {
            addCriterion("ELEC_TYPE_CODE in", values, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeNotIn(List<String> values) {
            addCriterion("ELEC_TYPE_CODE not in", values, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeBetween(String value1, String value2) {
            addCriterion("ELEC_TYPE_CODE between", value1, value2, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andElecTypeCodeNotBetween(String value1, String value2) {
            addCriterion("ELEC_TYPE_CODE not between", value1, value2, "elecTypeCode");
            return (Criteria) this;
        }

        public Criteria andContractCapIsNull() {
            addCriterion("CONTRACT_CAP is null");
            return (Criteria) this;
        }

        public Criteria andContractCapIsNotNull() {
            addCriterion("CONTRACT_CAP is not null");
            return (Criteria) this;
        }

        public Criteria andContractCapEqualTo(Double value) {
            addCriterion("CONTRACT_CAP =", value, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapNotEqualTo(Double value) {
            addCriterion("CONTRACT_CAP <>", value, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapGreaterThan(Double value) {
            addCriterion("CONTRACT_CAP >", value, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapGreaterThanOrEqualTo(Double value) {
            addCriterion("CONTRACT_CAP >=", value, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapLessThan(Double value) {
            addCriterion("CONTRACT_CAP <", value, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapLessThanOrEqualTo(Double value) {
            addCriterion("CONTRACT_CAP <=", value, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapIn(List<Double> values) {
            addCriterion("CONTRACT_CAP in", values, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapNotIn(List<Double> values) {
            addCriterion("CONTRACT_CAP not in", values, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapBetween(Double value1, Double value2) {
            addCriterion("CONTRACT_CAP between", value1, value2, "contractCap");
            return (Criteria) this;
        }

        public Criteria andContractCapNotBetween(Double value1, Double value2) {
            addCriterion("CONTRACT_CAP not between", value1, value2, "contractCap");
            return (Criteria) this;
        }

        public Criteria andRunCapIsNull() {
            addCriterion("RUN_CAP is null");
            return (Criteria) this;
        }

        public Criteria andRunCapIsNotNull() {
            addCriterion("RUN_CAP is not null");
            return (Criteria) this;
        }

        public Criteria andRunCapEqualTo(Double value) {
            addCriterion("RUN_CAP =", value, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapNotEqualTo(Double value) {
            addCriterion("RUN_CAP <>", value, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapGreaterThan(Double value) {
            addCriterion("RUN_CAP >", value, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapGreaterThanOrEqualTo(Double value) {
            addCriterion("RUN_CAP >=", value, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapLessThan(Double value) {
            addCriterion("RUN_CAP <", value, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapLessThanOrEqualTo(Double value) {
            addCriterion("RUN_CAP <=", value, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapIn(List<Double> values) {
            addCriterion("RUN_CAP in", values, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapNotIn(List<Double> values) {
            addCriterion("RUN_CAP not in", values, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapBetween(Double value1, Double value2) {
            addCriterion("RUN_CAP between", value1, value2, "runCap");
            return (Criteria) this;
        }

        public Criteria andRunCapNotBetween(Double value1, Double value2) {
            addCriterion("RUN_CAP not between", value1, value2, "runCap");
            return (Criteria) this;
        }

        public Criteria andShiftNoIsNull() {
            addCriterion("SHIFT_NO is null");
            return (Criteria) this;
        }

        public Criteria andShiftNoIsNotNull() {
            addCriterion("SHIFT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andShiftNoEqualTo(String value) {
            addCriterion("SHIFT_NO =", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoNotEqualTo(String value) {
            addCriterion("SHIFT_NO <>", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoGreaterThan(String value) {
            addCriterion("SHIFT_NO >", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoGreaterThanOrEqualTo(String value) {
            addCriterion("SHIFT_NO >=", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoLessThan(String value) {
            addCriterion("SHIFT_NO <", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoLessThanOrEqualTo(String value) {
            addCriterion("SHIFT_NO <=", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoLike(String value) {
            addCriterion("SHIFT_NO like", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoNotLike(String value) {
            addCriterion("SHIFT_NO not like", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoIn(List<String> values) {
            addCriterion("SHIFT_NO in", values, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoNotIn(List<String> values) {
            addCriterion("SHIFT_NO not in", values, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoBetween(String value1, String value2) {
            addCriterion("SHIFT_NO between", value1, value2, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoNotBetween(String value1, String value2) {
            addCriterion("SHIFT_NO not between", value1, value2, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeIsNull() {
            addCriterion("LODE_ATTR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeIsNotNull() {
            addCriterion("LODE_ATTR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeEqualTo(String value) {
            addCriterion("LODE_ATTR_CODE =", value, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeNotEqualTo(String value) {
            addCriterion("LODE_ATTR_CODE <>", value, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeGreaterThan(String value) {
            addCriterion("LODE_ATTR_CODE >", value, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("LODE_ATTR_CODE >=", value, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeLessThan(String value) {
            addCriterion("LODE_ATTR_CODE <", value, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeLessThanOrEqualTo(String value) {
            addCriterion("LODE_ATTR_CODE <=", value, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeLike(String value) {
            addCriterion("LODE_ATTR_CODE like", value, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeNotLike(String value) {
            addCriterion("LODE_ATTR_CODE not like", value, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeIn(List<String> values) {
            addCriterion("LODE_ATTR_CODE in", values, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeNotIn(List<String> values) {
            addCriterion("LODE_ATTR_CODE not in", values, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeBetween(String value1, String value2) {
            addCriterion("LODE_ATTR_CODE between", value1, value2, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andLodeAttrCodeNotBetween(String value1, String value2) {
            addCriterion("LODE_ATTR_CODE not between", value1, value2, "lodeAttrCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeIsNull() {
            addCriterion("VOLT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andVoltCodeIsNotNull() {
            addCriterion("VOLT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andVoltCodeEqualTo(String value) {
            addCriterion("VOLT_CODE =", value, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeNotEqualTo(String value) {
            addCriterion("VOLT_CODE <>", value, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeGreaterThan(String value) {
            addCriterion("VOLT_CODE >", value, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeGreaterThanOrEqualTo(String value) {
            addCriterion("VOLT_CODE >=", value, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeLessThan(String value) {
            addCriterion("VOLT_CODE <", value, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeLessThanOrEqualTo(String value) {
            addCriterion("VOLT_CODE <=", value, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeLike(String value) {
            addCriterion("VOLT_CODE like", value, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeNotLike(String value) {
            addCriterion("VOLT_CODE not like", value, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeIn(List<String> values) {
            addCriterion("VOLT_CODE in", values, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeNotIn(List<String> values) {
            addCriterion("VOLT_CODE not in", values, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeBetween(String value1, String value2) {
            addCriterion("VOLT_CODE between", value1, value2, "voltCode");
            return (Criteria) this;
        }

        public Criteria andVoltCodeNotBetween(String value1, String value2) {
            addCriterion("VOLT_CODE not between", value1, value2, "voltCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeIsNull() {
            addCriterion("HEC_INDUSTRY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeIsNotNull() {
            addCriterion("HEC_INDUSTRY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeEqualTo(String value) {
            addCriterion("HEC_INDUSTRY_CODE =", value, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeNotEqualTo(String value) {
            addCriterion("HEC_INDUSTRY_CODE <>", value, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeGreaterThan(String value) {
            addCriterion("HEC_INDUSTRY_CODE >", value, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("HEC_INDUSTRY_CODE >=", value, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeLessThan(String value) {
            addCriterion("HEC_INDUSTRY_CODE <", value, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeLessThanOrEqualTo(String value) {
            addCriterion("HEC_INDUSTRY_CODE <=", value, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeLike(String value) {
            addCriterion("HEC_INDUSTRY_CODE like", value, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeNotLike(String value) {
            addCriterion("HEC_INDUSTRY_CODE not like", value, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeIn(List<String> values) {
            addCriterion("HEC_INDUSTRY_CODE in", values, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeNotIn(List<String> values) {
            addCriterion("HEC_INDUSTRY_CODE not in", values, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeBetween(String value1, String value2) {
            addCriterion("HEC_INDUSTRY_CODE between", value1, value2, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHecIndustryCodeNotBetween(String value1, String value2) {
            addCriterion("HEC_INDUSTRY_CODE not between", value1, value2, "hecIndustryCode");
            return (Criteria) this;
        }

        public Criteria andHolidayIsNull() {
            addCriterion("HOLIDAY is null");
            return (Criteria) this;
        }

        public Criteria andHolidayIsNotNull() {
            addCriterion("HOLIDAY is not null");
            return (Criteria) this;
        }

        public Criteria andHolidayEqualTo(String value) {
            addCriterion("HOLIDAY =", value, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayNotEqualTo(String value) {
            addCriterion("HOLIDAY <>", value, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayGreaterThan(String value) {
            addCriterion("HOLIDAY >", value, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayGreaterThanOrEqualTo(String value) {
            addCriterion("HOLIDAY >=", value, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayLessThan(String value) {
            addCriterion("HOLIDAY <", value, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayLessThanOrEqualTo(String value) {
            addCriterion("HOLIDAY <=", value, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayLike(String value) {
            addCriterion("HOLIDAY like", value, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayNotLike(String value) {
            addCriterion("HOLIDAY not like", value, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayIn(List<String> values) {
            addCriterion("HOLIDAY in", values, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayNotIn(List<String> values) {
            addCriterion("HOLIDAY not in", values, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayBetween(String value1, String value2) {
            addCriterion("HOLIDAY between", value1, value2, "holiday");
            return (Criteria) this;
        }

        public Criteria andHolidayNotBetween(String value1, String value2) {
            addCriterion("HOLIDAY not between", value1, value2, "holiday");
            return (Criteria) this;
        }

        public Criteria andBuildDateIsNull() {
            addCriterion("BUILD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBuildDateIsNotNull() {
            addCriterion("BUILD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBuildDateEqualTo(Date value) {
            addCriterionForJDBCDate("BUILD_DATE =", value, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("BUILD_DATE <>", value, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateGreaterThan(Date value) {
            addCriterionForJDBCDate("BUILD_DATE >", value, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("BUILD_DATE >=", value, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateLessThan(Date value) {
            addCriterionForJDBCDate("BUILD_DATE <", value, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("BUILD_DATE <=", value, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateIn(List<Date> values) {
            addCriterionForJDBCDate("BUILD_DATE in", values, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("BUILD_DATE not in", values, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("BUILD_DATE between", value1, value2, "buildDate");
            return (Criteria) this;
        }

        public Criteria andBuildDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("BUILD_DATE not between", value1, value2, "buildDate");
            return (Criteria) this;
        }

        public Criteria andPsDateIsNull() {
            addCriterion("PS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPsDateIsNotNull() {
            addCriterion("PS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPsDateEqualTo(Date value) {
            addCriterionForJDBCDate("PS_DATE =", value, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PS_DATE <>", value, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateGreaterThan(Date value) {
            addCriterionForJDBCDate("PS_DATE >", value, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PS_DATE >=", value, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateLessThan(Date value) {
            addCriterionForJDBCDate("PS_DATE <", value, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PS_DATE <=", value, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateIn(List<Date> values) {
            addCriterionForJDBCDate("PS_DATE in", values, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PS_DATE not in", values, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PS_DATE between", value1, value2, "psDate");
            return (Criteria) this;
        }

        public Criteria andPsDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PS_DATE not between", value1, value2, "psDate");
            return (Criteria) this;
        }

        public Criteria andDueDateIsNull() {
            addCriterion("DUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDueDateIsNotNull() {
            addCriterion("DUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDueDateEqualTo(Date value) {
            addCriterionForJDBCDate("DUE_DATE =", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("DUE_DATE <>", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateGreaterThan(Date value) {
            addCriterionForJDBCDate("DUE_DATE >", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DUE_DATE >=", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateLessThan(Date value) {
            addCriterionForJDBCDate("DUE_DATE <", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DUE_DATE <=", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateIn(List<Date> values) {
            addCriterionForJDBCDate("DUE_DATE in", values, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("DUE_DATE not in", values, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DUE_DATE between", value1, value2, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DUE_DATE not between", value1, value2, "dueDate");
            return (Criteria) this;
        }

        public Criteria andNotifyModeIsNull() {
            addCriterion("NOTIFY_MODE is null");
            return (Criteria) this;
        }

        public Criteria andNotifyModeIsNotNull() {
            addCriterion("NOTIFY_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyModeEqualTo(String value) {
            addCriterion("NOTIFY_MODE =", value, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeNotEqualTo(String value) {
            addCriterion("NOTIFY_MODE <>", value, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeGreaterThan(String value) {
            addCriterion("NOTIFY_MODE >", value, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeGreaterThanOrEqualTo(String value) {
            addCriterion("NOTIFY_MODE >=", value, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeLessThan(String value) {
            addCriterion("NOTIFY_MODE <", value, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeLessThanOrEqualTo(String value) {
            addCriterion("NOTIFY_MODE <=", value, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeLike(String value) {
            addCriterion("NOTIFY_MODE like", value, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeNotLike(String value) {
            addCriterion("NOTIFY_MODE not like", value, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeIn(List<String> values) {
            addCriterion("NOTIFY_MODE in", values, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeNotIn(List<String> values) {
            addCriterion("NOTIFY_MODE not in", values, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeBetween(String value1, String value2) {
            addCriterion("NOTIFY_MODE between", value1, value2, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andNotifyModeNotBetween(String value1, String value2) {
            addCriterion("NOTIFY_MODE not between", value1, value2, "notifyMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeIsNull() {
            addCriterion("SETTLE_MODE is null");
            return (Criteria) this;
        }

        public Criteria andSettleModeIsNotNull() {
            addCriterion("SETTLE_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andSettleModeEqualTo(String value) {
            addCriterion("SETTLE_MODE =", value, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeNotEqualTo(String value) {
            addCriterion("SETTLE_MODE <>", value, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeGreaterThan(String value) {
            addCriterion("SETTLE_MODE >", value, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLE_MODE >=", value, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeLessThan(String value) {
            addCriterion("SETTLE_MODE <", value, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeLessThanOrEqualTo(String value) {
            addCriterion("SETTLE_MODE <=", value, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeLike(String value) {
            addCriterion("SETTLE_MODE like", value, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeNotLike(String value) {
            addCriterion("SETTLE_MODE not like", value, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeIn(List<String> values) {
            addCriterion("SETTLE_MODE in", values, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeNotIn(List<String> values) {
            addCriterion("SETTLE_MODE not in", values, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeBetween(String value1, String value2) {
            addCriterion("SETTLE_MODE between", value1, value2, "settleMode");
            return (Criteria) this;
        }

        public Criteria andSettleModeNotBetween(String value1, String value2) {
            addCriterion("SETTLE_MODE not between", value1, value2, "settleMode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIsNull() {
            addCriterion("STATUS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIsNotNull() {
            addCriterion("STATUS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andStatusCodeEqualTo(String value) {
            addCriterion("STATUS_CODE =", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotEqualTo(String value) {
            addCriterion("STATUS_CODE <>", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeGreaterThan(String value) {
            addCriterion("STATUS_CODE >", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS_CODE >=", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeLessThan(String value) {
            addCriterion("STATUS_CODE <", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeLessThanOrEqualTo(String value) {
            addCriterion("STATUS_CODE <=", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeLike(String value) {
            addCriterion("STATUS_CODE like", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotLike(String value) {
            addCriterion("STATUS_CODE not like", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIn(List<String> values) {
            addCriterion("STATUS_CODE in", values, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotIn(List<String> values) {
            addCriterion("STATUS_CODE not in", values, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeBetween(String value1, String value2) {
            addCriterion("STATUS_CODE between", value1, value2, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotBetween(String value1, String value2) {
            addCriterion("STATUS_CODE not between", value1, value2, "statusCode");
            return (Criteria) this;
        }

        public Criteria andOrgNoIsNull() {
            addCriterion("ORG_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrgNoIsNotNull() {
            addCriterion("ORG_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNoEqualTo(String value) {
            addCriterion("ORG_NO =", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoNotEqualTo(String value) {
            addCriterion("ORG_NO <>", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoGreaterThan(String value) {
            addCriterion("ORG_NO >", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NO >=", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoLessThan(String value) {
            addCriterion("ORG_NO <", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoLessThanOrEqualTo(String value) {
            addCriterion("ORG_NO <=", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoLike(String value) {
            addCriterion("ORG_NO like", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoNotLike(String value) {
            addCriterion("ORG_NO not like", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoIn(List<String> values) {
            addCriterion("ORG_NO in", values, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoNotIn(List<String> values) {
            addCriterion("ORG_NO not in", values, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoBetween(String value1, String value2) {
            addCriterion("ORG_NO between", value1, value2, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoNotBetween(String value1, String value2) {
            addCriterion("ORG_NO not between", value1, value2, "orgNo");
            return (Criteria) this;
        }

        public Criteria andRrioCodeIsNull() {
            addCriterion("RRIO_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRrioCodeIsNotNull() {
            addCriterion("RRIO_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRrioCodeEqualTo(String value) {
            addCriterion("RRIO_CODE =", value, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeNotEqualTo(String value) {
            addCriterion("RRIO_CODE <>", value, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeGreaterThan(String value) {
            addCriterion("RRIO_CODE >", value, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RRIO_CODE >=", value, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeLessThan(String value) {
            addCriterion("RRIO_CODE <", value, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeLessThanOrEqualTo(String value) {
            addCriterion("RRIO_CODE <=", value, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeLike(String value) {
            addCriterion("RRIO_CODE like", value, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeNotLike(String value) {
            addCriterion("RRIO_CODE not like", value, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeIn(List<String> values) {
            addCriterion("RRIO_CODE in", values, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeNotIn(List<String> values) {
            addCriterion("RRIO_CODE not in", values, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeBetween(String value1, String value2) {
            addCriterion("RRIO_CODE between", value1, value2, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andRrioCodeNotBetween(String value1, String value2) {
            addCriterion("RRIO_CODE not between", value1, value2, "rrioCode");
            return (Criteria) this;
        }

        public Criteria andChkCycleIsNull() {
            addCriterion("CHK_CYCLE is null");
            return (Criteria) this;
        }

        public Criteria andChkCycleIsNotNull() {
            addCriterion("CHK_CYCLE is not null");
            return (Criteria) this;
        }

        public Criteria andChkCycleEqualTo(String value) {
            addCriterion("CHK_CYCLE =", value, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleNotEqualTo(String value) {
            addCriterion("CHK_CYCLE <>", value, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleGreaterThan(String value) {
            addCriterion("CHK_CYCLE >", value, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_CYCLE >=", value, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleLessThan(String value) {
            addCriterion("CHK_CYCLE <", value, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleLessThanOrEqualTo(String value) {
            addCriterion("CHK_CYCLE <=", value, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleLike(String value) {
            addCriterion("CHK_CYCLE like", value, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleNotLike(String value) {
            addCriterion("CHK_CYCLE not like", value, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleIn(List<String> values) {
            addCriterion("CHK_CYCLE in", values, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleNotIn(List<String> values) {
            addCriterion("CHK_CYCLE not in", values, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleBetween(String value1, String value2) {
            addCriterion("CHK_CYCLE between", value1, value2, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andChkCycleNotBetween(String value1, String value2) {
            addCriterion("CHK_CYCLE not between", value1, value2, "chkCycle");
            return (Criteria) this;
        }

        public Criteria andLastChkDateIsNull() {
            addCriterion("LAST_CHK_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastChkDateIsNotNull() {
            addCriterion("LAST_CHK_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastChkDateEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_CHK_DATE =", value, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_CHK_DATE <>", value, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateGreaterThan(Date value) {
            addCriterionForJDBCDate("LAST_CHK_DATE >", value, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_CHK_DATE >=", value, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateLessThan(Date value) {
            addCriterionForJDBCDate("LAST_CHK_DATE <", value, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_CHK_DATE <=", value, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateIn(List<Date> values) {
            addCriterionForJDBCDate("LAST_CHK_DATE in", values, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("LAST_CHK_DATE not in", values, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_CHK_DATE between", value1, value2, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andLastChkDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_CHK_DATE not between", value1, value2, "lastChkDate");
            return (Criteria) this;
        }

        public Criteria andChecerNoIsNull() {
            addCriterion("CHECER_NO is null");
            return (Criteria) this;
        }

        public Criteria andChecerNoIsNotNull() {
            addCriterion("CHECER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andChecerNoEqualTo(String value) {
            addCriterion("CHECER_NO =", value, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoNotEqualTo(String value) {
            addCriterion("CHECER_NO <>", value, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoGreaterThan(String value) {
            addCriterion("CHECER_NO >", value, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoGreaterThanOrEqualTo(String value) {
            addCriterion("CHECER_NO >=", value, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoLessThan(String value) {
            addCriterion("CHECER_NO <", value, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoLessThanOrEqualTo(String value) {
            addCriterion("CHECER_NO <=", value, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoLike(String value) {
            addCriterion("CHECER_NO like", value, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoNotLike(String value) {
            addCriterion("CHECER_NO not like", value, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoIn(List<String> values) {
            addCriterion("CHECER_NO in", values, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoNotIn(List<String> values) {
            addCriterion("CHECER_NO not in", values, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoBetween(String value1, String value2) {
            addCriterion("CHECER_NO between", value1, value2, "checerNo");
            return (Criteria) this;
        }

        public Criteria andChecerNoNotBetween(String value1, String value2) {
            addCriterion("CHECER_NO not between", value1, value2, "checerNo");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeIsNull() {
            addCriterion("POWEROFF_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeIsNotNull() {
            addCriterion("POWEROFF_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeEqualTo(String value) {
            addCriterion("POWEROFF_CODE =", value, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeNotEqualTo(String value) {
            addCriterion("POWEROFF_CODE <>", value, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeGreaterThan(String value) {
            addCriterion("POWEROFF_CODE >", value, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeGreaterThanOrEqualTo(String value) {
            addCriterion("POWEROFF_CODE >=", value, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeLessThan(String value) {
            addCriterion("POWEROFF_CODE <", value, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeLessThanOrEqualTo(String value) {
            addCriterion("POWEROFF_CODE <=", value, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeLike(String value) {
            addCriterion("POWEROFF_CODE like", value, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeNotLike(String value) {
            addCriterion("POWEROFF_CODE not like", value, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeIn(List<String> values) {
            addCriterion("POWEROFF_CODE in", values, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeNotIn(List<String> values) {
            addCriterion("POWEROFF_CODE not in", values, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeBetween(String value1, String value2) {
            addCriterion("POWEROFF_CODE between", value1, value2, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andPoweroffCodeNotBetween(String value1, String value2) {
            addCriterion("POWEROFF_CODE not between", value1, value2, "poweroffCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeIsNull() {
            addCriterion("TRANSFER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTransferCodeIsNotNull() {
            addCriterion("TRANSFER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTransferCodeEqualTo(String value) {
            addCriterion("TRANSFER_CODE =", value, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeNotEqualTo(String value) {
            addCriterion("TRANSFER_CODE <>", value, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeGreaterThan(String value) {
            addCriterion("TRANSFER_CODE >", value, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFER_CODE >=", value, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeLessThan(String value) {
            addCriterion("TRANSFER_CODE <", value, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeLessThanOrEqualTo(String value) {
            addCriterion("TRANSFER_CODE <=", value, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeLike(String value) {
            addCriterion("TRANSFER_CODE like", value, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeNotLike(String value) {
            addCriterion("TRANSFER_CODE not like", value, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeIn(List<String> values) {
            addCriterion("TRANSFER_CODE in", values, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeNotIn(List<String> values) {
            addCriterion("TRANSFER_CODE not in", values, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeBetween(String value1, String value2) {
            addCriterion("TRANSFER_CODE between", value1, value2, "transferCode");
            return (Criteria) this;
        }

        public Criteria andTransferCodeNotBetween(String value1, String value2) {
            addCriterion("TRANSFER_CODE not between", value1, value2, "transferCode");
            return (Criteria) this;
        }

        public Criteria andMrSectNoIsNull() {
            addCriterion("MR_SECT_NO is null");
            return (Criteria) this;
        }

        public Criteria andMrSectNoIsNotNull() {
            addCriterion("MR_SECT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMrSectNoEqualTo(String value) {
            addCriterion("MR_SECT_NO =", value, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoNotEqualTo(String value) {
            addCriterion("MR_SECT_NO <>", value, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoGreaterThan(String value) {
            addCriterion("MR_SECT_NO >", value, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoGreaterThanOrEqualTo(String value) {
            addCriterion("MR_SECT_NO >=", value, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoLessThan(String value) {
            addCriterion("MR_SECT_NO <", value, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoLessThanOrEqualTo(String value) {
            addCriterion("MR_SECT_NO <=", value, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoLike(String value) {
            addCriterion("MR_SECT_NO like", value, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoNotLike(String value) {
            addCriterion("MR_SECT_NO not like", value, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoIn(List<String> values) {
            addCriterion("MR_SECT_NO in", values, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoNotIn(List<String> values) {
            addCriterion("MR_SECT_NO not in", values, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoBetween(String value1, String value2) {
            addCriterion("MR_SECT_NO between", value1, value2, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andMrSectNoNotBetween(String value1, String value2) {
            addCriterion("MR_SECT_NO not between", value1, value2, "mrSectNo");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeIsNull() {
            addCriterion("NOTE_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeIsNotNull() {
            addCriterion("NOTE_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeEqualTo(String value) {
            addCriterion("NOTE_TYPE_CODE =", value, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeNotEqualTo(String value) {
            addCriterion("NOTE_TYPE_CODE <>", value, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeGreaterThan(String value) {
            addCriterion("NOTE_TYPE_CODE >", value, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE_TYPE_CODE >=", value, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeLessThan(String value) {
            addCriterion("NOTE_TYPE_CODE <", value, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("NOTE_TYPE_CODE <=", value, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeLike(String value) {
            addCriterion("NOTE_TYPE_CODE like", value, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeNotLike(String value) {
            addCriterion("NOTE_TYPE_CODE not like", value, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeIn(List<String> values) {
            addCriterion("NOTE_TYPE_CODE in", values, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeNotIn(List<String> values) {
            addCriterion("NOTE_TYPE_CODE not in", values, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeBetween(String value1, String value2) {
            addCriterion("NOTE_TYPE_CODE between", value1, value2, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andNoteTypeCodeNotBetween(String value1, String value2) {
            addCriterion("NOTE_TYPE_CODE not between", value1, value2, "noteTypeCode");
            return (Criteria) this;
        }

        public Criteria andTmpFlagIsNull() {
            addCriterion("TMP_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andTmpFlagIsNotNull() {
            addCriterion("TMP_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andTmpFlagEqualTo(String value) {
            addCriterion("TMP_FLAG =", value, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagNotEqualTo(String value) {
            addCriterion("TMP_FLAG <>", value, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagGreaterThan(String value) {
            addCriterion("TMP_FLAG >", value, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagGreaterThanOrEqualTo(String value) {
            addCriterion("TMP_FLAG >=", value, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagLessThan(String value) {
            addCriterion("TMP_FLAG <", value, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagLessThanOrEqualTo(String value) {
            addCriterion("TMP_FLAG <=", value, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagLike(String value) {
            addCriterion("TMP_FLAG like", value, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagNotLike(String value) {
            addCriterion("TMP_FLAG not like", value, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagIn(List<String> values) {
            addCriterion("TMP_FLAG in", values, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagNotIn(List<String> values) {
            addCriterion("TMP_FLAG not in", values, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagBetween(String value1, String value2) {
            addCriterion("TMP_FLAG between", value1, value2, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpFlagNotBetween(String value1, String value2) {
            addCriterion("TMP_FLAG not between", value1, value2, "tmpFlag");
            return (Criteria) this;
        }

        public Criteria andTmpDateIsNull() {
            addCriterion("TMP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTmpDateIsNotNull() {
            addCriterion("TMP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTmpDateEqualTo(Date value) {
            addCriterionForJDBCDate("TMP_DATE =", value, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("TMP_DATE <>", value, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateGreaterThan(Date value) {
            addCriterionForJDBCDate("TMP_DATE >", value, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TMP_DATE >=", value, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateLessThan(Date value) {
            addCriterionForJDBCDate("TMP_DATE <", value, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TMP_DATE <=", value, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateIn(List<Date> values) {
            addCriterionForJDBCDate("TMP_DATE in", values, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("TMP_DATE not in", values, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TMP_DATE between", value1, value2, "tmpDate");
            return (Criteria) this;
        }

        public Criteria andTmpDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TMP_DATE not between", value1, value2, "tmpDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_cons
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 02 13:03:25 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_cons
     *
     * @mbggenerated Sun Aug 02 13:03:25 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}